---
- name: configure...
  become: yes
  become_user: root
  with_items:
    - zoo.cfg
    - log4j.properties
  template: >-
    src=conf/{{item}}.j2
    dest={{zookeeper_conf_dir}}/{{item}}

- name: ensure the data subdir exists
  become: yes
  become_user: root
  file: >-
    path={{zookeeper_data_dir}}
    state=directory
    mode=0700
    
- name: configure...
  become: yes
  become_user: root
  with_items:
    - myid
  template: >-
    src=data/{{item}}.j2
    dest={{zookeeper_data_dir}}/{{item}}
    
- name: configurating init system
  include: '{{zookeeper_init_system|default(systemd)}}.yml'
